version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: island_camping19
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      
