CREATE SEQUENCE user_type_id_sequence;
CREATE TABLE USER_TYPE(
    ID INTEGER NOT NULL DEFAULT nextval('user_type_id_sequence'),
    TYPE VARCHAR(32) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(256) DEFAULT NULL,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE status_id_sequence;
CREATE TABLE STATUS(
    ID INTEGER NOT NULL DEFAULT nextval('status_id_sequence'),
    CODE VARCHAR(32) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(256) DEFAULT NULL,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE user_id_sequence;
CREATE TABLE RESERVATION_USER(
    VERSION INTEGER NOT NULL DEFAULT 0,
    ID INTEGER NOT NULL DEFAULT nextval('user_id_sequence'),
    FIRST_NAME VARCHAR(256) NOT NULL ,
    LAST_NAME VARCHAR(256) NOT NULL ,
    EMAIL VARCHAR(256) NOT NULL ,
    STATUS_ID INTEGER NOT NULL REFERENCES STATUS(ID),
    USER_TYPE_ID INTEGER NOT NULL REFERENCES USER_TYPE(ID),
    CREATION_DATE TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);

