CREATE SEQUENCE status_id_sequence;
CREATE TABLE STATUS
(
   ID INTEGER NOT NULL DEFAULT nextval('status_id_sequence'),
   VERSION INTEGER NOT NULL DEFAULT 0,
   CODE VARCHAR(32) NOT NULL UNIQUE,
   DESCRIPTION VARCHAR(256) DEFAULT NULL,
   PRIMARY KEY (ID)
);