CREATE SEQUENCE user_id_sequence;
CREATE TABLE ISLAND_USER
(
    ID         INTEGER      NOT NULL DEFAULT nextval('user_id_sequence'),
    VERSION    INTEGER      NOT NULL DEFAULT 0,
    FIRST_NAME VARCHAR(256) NOT NULL,
    LAST_NAME  VARCHAR(256) NOT NULL,
    EMAIL      VARCHAR(256) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX user_email_idx ON ISLAND_USER (EMAIL);

ALTER TABLE ISLAND_USER
    ADD CONSTRAINT unique_user_id
        UNIQUE USING INDEX user_email_idx;