CREATE SEQUENCE spot_id_sequence;
CREATE TABLE SPOT(
    ID INTEGER NOT NULL DEFAULT nextval('spot_id_sequence'),
    NAME VARCHAR(256) DEFAULT NULL,
    DESCRIPTION VARCHAR(256) DEFAULT NULL,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE availability_id_sequence;
CREATE TABLE AVAILABILITY(
    ID INTEGER NOT NULL DEFAULT nextval('availability_id_sequence'),
    SPOT_ID INTEGER NOT NULL REFERENCES SPOT(ID),
    AVAILABLE_DATE DATE NOT NULL UNIQUE ,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE reservation_id_sequence;
CREATE TABLE RESERVATION(
    ID INTEGER NOT NULL DEFAULT nextval('reservation_id_sequence'),
    UUID VARCHAR(32) NOT NULL UNIQUE ,
    USER_ID INTEGER NOT NULL REFERENCES RESERVATION_USER(ID),
    STATUS_ID INTEGER NOT NULL REFERENCES STATUS(ID),
    AVAILABILITY_ID INTEGER NOT NULL REFERENCES AVAILABILITY(ID),
    PRICE INTEGER NOT NULL DEFAULT 0,
    ARRIVAL_DATE DATE NOT NULL,
    DEPARTURE_DATE DATE NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,
    UPDATE_DATE TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);

