CREATE SEQUENCE spot_id_sequence;
CREATE TABLE SPOT
(
     ID INTEGER NOT NULL DEFAULT nextval('spot_id_sequence'),
     VERSION INTEGER NOT NULL DEFAULT 0,
     NAME VARCHAR(256) DEFAULT NULL,
     DESCRIPTION VARCHAR(256) DEFAULT NULL,
     PRIMARY KEY (ID)
);