CREATE SEQUENCE availability_id_sequence;
CREATE TABLE AVAILABILITY
(
    ID INTEGER NOT NULL DEFAULT nextval('availability_id_sequence'),
    VERSION INTEGER NOT NULL DEFAULT 0,
    AVAILABLE_DATE DATE NOT NULL UNIQUE,
    STATUS_ID INTEGER NOT NULL REFERENCES STATUS(ID),
    PRIMARY KEY (ID)
);