CREATE SEQUENCE reservation_id_sequence;
CREATE TABLE RESERVATION
(
    ID INTEGER NOT NULL DEFAULT nextval('reservation_id_sequence'),
    VERSION INTEGER NOT NULL DEFAULT 0,
    BOOKING_UUID VARCHAR(32) NOT NULL UNIQUE ,
    STATUS_ID INTEGER NOT NULL REFERENCES STATUS(ID),
    USER_ID INTEGER NOT NULL REFERENCES ISLAND_USER(ID),
    SPOT_ID INTEGER NOT NULL REFERENCES SPOT(ID),
    PRICE INTEGER NOT NULL DEFAULT 0,
    ARRIVAL_DATE DATE NOT NULL,
    DEPARTURE_DATE DATE NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,
    UPDATE_DATE TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);