CREATE SEQUENCE reservation_id_sequence;
CREATE TABLE RESERVATION
(
    ID INTEGER NOT NULL DEFAULT nextval('reservation_id_sequence'),
    VERSION INTEGER NOT NULL DEFAULT 0,
    BOOKING_UUID VARCHAR(40) NOT NULL ,
    STATUS_ID INTEGER NOT NULL REFERENCES STATUS(ID),
    USER_ID INTEGER NOT NULL REFERENCES ISLAND_USER(ID),
    SPOT_ID INTEGER NOT NULL REFERENCES SPOT(ID),
    PRICE INTEGER NOT NULL DEFAULT 0,
    ARRIVAL_DATE DATE NOT NULL,
    DEPARTURE_DATE DATE NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,
    UPDATE_DATE TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX reservation_booking_uuid_idx ON RESERVATION(BOOKING_UUID);

ALTER TABLE RESERVATION
    ADD CONSTRAINT unique_reservation_booking_id
        UNIQUE USING INDEX reservation_booking_uuid_idx;