CREATE SEQUENCE reserved_date_id_sequence;
CREATE TABLE RESERVED_DATE
(
    ID INTEGER NOT NULL DEFAULT nextval('reserved_date_id_sequence'),
    VERSION INTEGER NOT NULL DEFAULT 0,
    AVAILABILITY_ID INTEGER NOT NULL REFERENCES AVAILABILITY(ID),
    RESERVATION_ID INTEGER NOT NULL REFERENCES RESERVATION(ID),
    PRIMARY KEY (ID)
);