--STATUS
insert into public.STATUS(CODE,DESCRIPTION) values ('AVAILABLE','Resource is available');
insert into public.STATUS(CODE,DESCRIPTION) values ('RESERVED','Resource is reserved');
insert into public.STATUS(CODE,DESCRIPTION) values ('CANCELED','Resource is canceled');

--SPOT
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Retriever labrador','Retriever spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('German Shepherd Dogs	spot','German Shepherd Dogs spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Retrievers (Golden)','Retrievers (Golden)  spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('French Bulldogs','French Bulldogs spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Poodles','Poodles spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Beagles','Beagles spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Rottweilers','Rottweilers spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Pembroke Welsh Corgis','Pembroke Welsh Corgis spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Yorkshire Terriers','Yorkshire Terriers spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Australian Shepherds	spot','Australian Shepherds spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Boxers','Boxers spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Siberian Huskies	spot','Siberian Huskies spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Doberman Pinschers','Doberman Pinschers spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Shih Tzu	spot','Shih Tzu spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Boston Terriers','Boston Terriers spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Havanese	spot','Havanese spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Bernese Mountain','Bernese Mountain spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Pomeranians','Pomeranians spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Shetland Sheepdogs','Shetland Sheepdogs spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Brittanys','Brittanys spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Spaniels (English Springer)','Spaniels (English Springer) spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Spaniels (Cocker)','Spaniels (Cocker) spot spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Miniature American Shepherds	spot','Miniature American Shepherds spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Cane Corso','Cane Corso spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Pugs	spot','Pugs spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Mastiffs	spot','Mastiffs spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Border Collies','Border Collies spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Vizslas','Vizslas spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Chihuahuas','Chihuahuas spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Maltese','Maltese spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Basset Hounds','Basset Hounds spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Collies','Collies spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Weimaraners','Weimaraners spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Newfoundlands','Newfoundlands spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Belgian Malinois','Belgian Malinois spot',1);

--AVAILABILITY
--March 2021 is available for booking
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-02-15',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-02-16',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-02-17',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-02-18',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-02-19',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-02-20',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-02-21',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-02-22',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-02-23',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-02-24',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-02-25',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-02-26',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-02-27',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-02-28',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-03-01',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-03-02',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-03-03',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-03-04',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-03-05',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-03-06',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-03-07',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-03-08',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-03-09',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-03-10',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-03-11',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-03-12',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-03-13',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-03-14',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-03-15',1);
