--STATUS
insert into public.STATUS(CODE,DESCRIPTION) values ('AVAILABLE','Spot is available');
insert into public.STATUS(CODE,DESCRIPTION) values ('RESERVED','Spot is reserved');
insert into public.STATUS(CODE,DESCRIPTION) values ('CANCELED','Spot is canceled');

--SPOT
insert into public.SPOT(NAME,DESCRIPTION) values ('Retriever labrador','Retriever spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('German Shepherd Dogs	spot','German Shepherd Dogs spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Retrievers (Golden)','Retrievers (Golden)  spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('French Bulldogs','French Bulldogs spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Poodles','Poodles spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Beagles','Beagles spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Rottweilers','Rottweilers spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Pembroke Welsh Corgis','Pembroke Welsh Corgis spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Yorkshire Terriers','Yorkshire Terriers spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Australian Shepherds	spot','Australian Shepherds spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Boxers','Boxers spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Siberian Huskies	spot','Siberian Huskies spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Doberman Pinschers','Doberman Pinschers spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Shih Tzu	spot','Shih Tzu spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Boston Terriers','Boston Terriers spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Havanese	spot','Havanese spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Bernese Mountain','Bernese Mountain spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Pomeranians','Pomeranians spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Shetland Sheepdogs','Shetland Sheepdogs spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Brittanys','Brittanys spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Spaniels (English Springer)','Spaniels (English Springer) spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Spaniels (Cocker)','Spaniels (Cocker) spot spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Miniature American Shepherds	spot','Miniature American Shepherds spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Cane Corso','Cane Corso spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Pugs	spot','Pugs spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Mastiffs	spot','Mastiffs spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Border Collies','Border Collies spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Vizslas','Vizslas spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Chihuahuas','Chihuahuas spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Maltese','Maltese spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Basset Hounds','Basset Hounds spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Collies','Collies spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Weimaraners','Weimaraners spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Newfoundlands','Newfoundlands spot');
insert into public.SPOT(NAME,DESCRIPTION) values ('Belgian Malinois','Belgian Malinois spot');

--SPOT
--June 2021 is available for booking
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-01',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-02',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-03',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-04',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-05',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-06',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-07',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-08',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-09',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-10',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-11',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-12',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-13',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-14',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-15',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-16',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-17',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-18',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-19',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-20',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-21',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-22',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-23',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-24',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-25',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-26',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-27',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-28',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-29',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-30',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-07-01',1);
