--STATUS
insert into public.STATUS(CODE,DESCRIPTION) values ('AVAILABLE','Resource is available');
insert into public.STATUS(CODE,DESCRIPTION) values ('RESERVED','Resource is reserved');
insert into public.STATUS(CODE,DESCRIPTION) values ('CANCELED','Resource is canceled');

--SPOT
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Retriever labrador','Retriever spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('German Shepherd Dogs	spot','German Shepherd Dogs spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Retrievers (Golden)','Retrievers (Golden)  spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('French Bulldogs','French Bulldogs spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Poodles','Poodles spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Beagles','Beagles spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Rottweilers','Rottweilers spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Pembroke Welsh Corgis','Pembroke Welsh Corgis spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Yorkshire Terriers','Yorkshire Terriers spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Australian Shepherds	spot','Australian Shepherds spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Boxers','Boxers spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Siberian Huskies	spot','Siberian Huskies spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Doberman Pinschers','Doberman Pinschers spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Shih Tzu	spot','Shih Tzu spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Boston Terriers','Boston Terriers spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Havanese	spot','Havanese spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Bernese Mountain','Bernese Mountain spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Pomeranians','Pomeranians spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Shetland Sheepdogs','Shetland Sheepdogs spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Brittanys','Brittanys spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Spaniels (English Springer)','Spaniels (English Springer) spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Spaniels (Cocker)','Spaniels (Cocker) spot spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Miniature American Shepherds	spot','Miniature American Shepherds spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Cane Corso','Cane Corso spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Pugs	spot','Pugs spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Mastiffs	spot','Mastiffs spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Border Collies','Border Collies spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Vizslas','Vizslas spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Chihuahuas','Chihuahuas spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Maltese','Maltese spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Basset Hounds','Basset Hounds spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Collies','Collies spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Weimaraners','Weimaraners spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Newfoundlands','Newfoundlands spot',1);
insert into public.SPOT(NAME,DESCRIPTION,STATUS_ID) values ('Belgian Malinois','Belgian Malinois spot',1);

--SPOT
--June 2021 is available for booking
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-01',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-02',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-03',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-04',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-05',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-06',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-07',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-08',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-09',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-10',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-11',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-12',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-13',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-14',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-15',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-16',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-17',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-18',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-19',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-20',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-21',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-22',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-23',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-24',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-25',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-26',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-27',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-28',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-29',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-06-30',1);
insert into public.AVAILABILITY(AVAILABLE_DATE,STATUS_ID) values ('2021-07-01',1);
